[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "pykarambola"
version = "0.1.0"
description = "Python implementation of Karambola â€“ Minkowski functionals and tensors on 3D triangulated surfaces"
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "scipy",
]

[project.optional-dependencies]
dev = ["pytest", "scikit-image"]
accel = ["cython>=3.0"]

[tool.setuptools.packages.find]
include = ["pykarambola*"]
